version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - SESSION_CONNECTION=sqlite
      - CACHE_STORE=database
      - QUEUE_CONNECTION=database
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./database:/var/www/html/database
    networks:
      - laravel

  # Optional: Uncomment if you want to use MySQL locally
  # db:
  #   image: mysql:8.0
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_USER: laravel
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: secret
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     - laravel

  # Optional: Uncomment if you want to use Redis locally
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - laravel

volumes:
  # mysql_data:
  # redis_data:

networks:
  laravel:
    driver: bridge
